version: '3.7'
volumes:
  pgdata:
services:
  db:
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_DB=londonapartmentbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: PGPASSWORD=password pg_isready -h 0.0.0.0 -U postgres -d londonapartmentbot
      interval: 5s
      retries: 2
  london_apartment_bot:
    build:
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
